---
- name: Setup Virtual Smart Cards for Ansible-FreeIPA Demo
  hosts: ipaclients
  vars:
    vsmartcard_repo: jjelen/vsmartcard
    test_dir: /opt/virtual_smartcard 
    sopin: 12345678
    pin: 123456
    libsofthsm: /usr/lib64/pkcs11/libsofthsm2.so
    softhsm_cfg: "{{ test_dir }}/softhsm2.conf"
    nssdb: "{{ test_dir }}/db"
    username: ipauser1
    ipaadmin_password: Secret123
  tasks:
    - name: Enable idm module
      shell: |
        set -e
        dnf -y module enable idm:DL1
        touch {{ test_dir }}/dnf_idm_enable.done
      when: ansible_distribution == "RedHat" and 
            ansible_distribution_major_version >= '8'
      args:
        creates: "{{ test_dir }}/dnf_idm_enable.done"        

    - name: Install basic RPMs
      package:
        name: "{{ item }}"
      loop:
        - opensc
        - openssl
        - gnutls-utils
        - softhsm
        - nss-tools

    - name: Enable vsmartcard copr repo
      command:
        cmd: dnf -y copr enable {{ vsmartcard_repo }}
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:jjelen:vsmartcard.repo

    - name: Install virtual smartcard packages
      package:
        name: "{{ item }}"
      loop:
        - virt_cacard
        - vpcd

    - name: Create test dir for virtual smartcards
      file:
        path: "{{ test_dir }}"
        state: directory

    - name: Create softhsm2 config
      copy:
        content: |
          directories.tokendir = {{ test_dir }}/tokens/
          slots.removable = true
          objectstore.backend = file
          log.level = INFO
        dest: "{{ softhsm_cfg }}"

    - name: Create tokens dir
      file: 
        path: "{{ test_dir }}/tokens"
        state: directory

    - name: Initialize softhsm2 token
      shell: |
        softhsm2-util --init-token --slot 0 --label "SC test" \
          --so-pin={{ sopin }} --pin={{ pin }}
      environment:
        SOFTHSM2_CONF: "{{ softhsm_cfg }}"
      args:
        chdir: "{{ test_dir }}"
        creates: "{{ test_dir }}/softhsm2_init.done"

    - name: Touch file to indicate softhsm2 initialize is done
      command:
        cmd: touch {{ test_dir }}/softhsm2_init.done
      args:
        creates: "{{ test_dir }}/softhsm2_init.done"

    - name: Create NSSDB
      file:
        path: "{{ nssdb }}"
        state: directory

    - name: modutil create NSSDB
      command:
        cmd: "modutil -create -dbdir sql:{{ nssdb }} -force"
      args:
        creates: "{{ nssdb }}/pkcs11.txt"

    - name: see if p11-kit-proxy configured
      shell: |
        modutil -list -dbdir sql:{{ nssdb }} -libfile {{ libsofthsm }} | \
          grep 'library name: p11-kit-proxy.so'
      ignore_errors: yes
      register: check_p11_kit_proxy

    - name: Add SoftHSM if p11-kit-proxy
      shell: |
        modutil -force -add 'SoftHSM PKCS#11' \
          -dbdir sql:{{ nssdb }} -libfile {{ libsofthsm }}
      when: check_p11_kit_proxy.rc == 1
  
    - name: Create pcscd semodule file
      copy:
        content: "(allow pcscd_t node_t (tcp_socket (node_bind)))"
        dest: "{{ test_dir }}/virtcacard.cil"

    - name: Install semodule
      shell: |
        set -e
        semodule -i {{ test_dir }}/virtcacard.cil
        touch {{ test_dir }}/virtcacard.cil.done
      args:
        chdir: "{{ test_dir }}"
        creates: "{{ test_dir }}/virtcacard.cil.done"

    - name: Copy pcscd service config file
      copy:
        src: /usr/lib/systemd/system/pcscd.service
        dest: /etc/systemd/system/pcscd.service
        remote_src: True

    - name: Remove --auto-exit from pcscd service
      replace:
        path: /etc/systemd/system/pcscd.service
        regexp: ' --auto-exit'

    - name: Copy virt_cacard.service file
      copy:
        content: |
          [Unit]
          Description=virt_cacard Service
          Requires=pcscd.service

          [Service]
          Environment=SOFTHSM2_CONF="{{ test_dir }}/softhsm2.conf"
          WorkingDirectory={{ test_dir }}
          ExecStart=/usr/bin/virt_cacard >> /var/log/virt_cacard.debug 2>&1
          KillMode=process

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/virt_cacard.service

    - name: disable virt_cacard in p11-kit opensc module
      lineinfile:
        path: /usr/share/p11-kit/modules/opensc.module
        line: "disable-in: virt_cacard"

    - name: Kinit as admin
      shell: echo {{ ipaadmin_password }} | kinit admin

    - name: Add IPA user
      shell: ipa user-add --first=f --last=l {{ username }}

    - name: Create User certificate signing request
      shell: |
        openssl req -new -newkey rsa:2048 -keyout {{ username }}.key \
          -nodes -out {{ username }}.csr -subj "/CN={{ username }}"
      args:
        chdir: "{{ test_dir }}"
    
    - name: Request Certificate from IPA for user
      shell: |
        ipa cert-request {{ username }}.csr --principal={{ username }} \
          --certificate-out={{ username }}.crt
      args:
        chdir: "{{ test_dir }}"

    - name: Add user key to softhsm token
      shell: |
        set -e
        pkcs11-tool --module libsofthsm2.so --slot-index 0 -w {{ username }}.key \
          -y privkey --label {{ username }} -p {{ pin }} --set-id 0 -d 0
        touch {{ test_dir }}/softhsm_add_user_key.done
      environment:
        SOFTHSM2_CONF: "{{ softhsm_cfg }}"
      args:
        chdir: "{{ test_dir }}"
        creates: "{{ test_dir }}/softhsm_add_user_key.done"

    - name: Add user certificate to softhsm token
      shell: |
        set -e
        pkcs11-tool --module libsofthsm2.so --slot-index 0 -w {{ username }}.crt \
          -y cert --label {{ username }} -p {{ pin }} --set-id 0 -d 0
        touch {{ test_dir }}/softhsm_add_user_cert.done
      environment:
        SOFTHSM2_CONF: "{{ softhsm_cfg }}"
      args:
        chdir: "{{ test_dir }}"
        creates: "{{ test_dir }}/softhsm_add_user_cert.done"

    - name: restart pcscd and virt_cacard
      systemd:
        name: "{{ item }}"
        daemon_reload: yes
        state: restarted
        enabled: yes
      loop:
        - pcscd
        - virt_cacard
